version: '3.7'
services:
  nodejs:
    image: node:15.14.0-slim
    container_name: node-express-jwt
    working_dir: /home/node/workspace
    tty: true
    volumes:
      - ./src:/home/node/workspace